graphite:
    host: 192.168.1.36
    port: 2003
spring:
    datasource:
        url: jdbc:postgresql://192.168.1.36:5432/integration
        username: postgres
        password: mysecretpassword
        initialize: false
    rabbitmq:
      host: 192.168.1.36
      username: guest
      password: guest

