spring:
    datasource:
        url: jdbc:postgresql://192.168.1.40:5432/integration
        username: postgres
        password: mysecretpassword
        initialization-mode: never
    rabbitmq:
      host: 192.168.1.40
      username: guest
      password: guest

management:
  metrics:
    export:
      prometheus:
        step: 1s
        pushgateway:
          base-url: 192.168.1.40:9091
          job: integration-monitoring
