spring:
    datasource:
        url: jdbc:postgresql://192.168.1.40:5432/integration
        username: postgres
        password: mysecretpassword
        initialization-mode: never
    rabbitmq:
      host: 192.168.1.40
      username: guest
      password: guest

management:
  metrics:
    export:
      graphite:
        host: 192.168.1.40
        step: 1s
        port: 2004
